# Generated by Django 5.1.2 on 2024-11-10 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isbn', models.TextField()),
                ('book_title', models.TextField()),
                ('book_author', models.TextField()),
                ('year_of_publication', models.TextField()),
                ('publisher', models.TextField()),
                ('image_url_s', models.URLField(max_length=1000)),
                ('image_url_m', models.URLField(max_length=1000)),
                ('image_url_l', models.URLField(max_length=1000)),
            ],
        ),
    ]
